// Generated by scripts/set-env.js — do not edit manually.
// Run `npm start` or `npm run build` to regenerate from .env
export const environment = {
  production: false,
  supabaseUrl: 'https://vnvywgtrdywfvrlrdgwq.supabase.co',
  supabaseKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZudnl3Z3RyZHl3ZnZybHJkZ3dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEzMzQzOTEsImV4cCI6MjA5NjkxMDM5MX0.NSBw9X03L-zvcG0m09LRE7WZW8iMI4lSzqSW2ZjYnG4',
};
