// Generated by scripts/set-env.js — do not edit manually.
// Run `node scripts/set-env.js` or `npm start` / `npm run build` to regenerate.
export const environment = {
  production: false,
  supabaseUrl: '',
  supabaseKey: '',
};
