// Generated by scripts/set-env.js — do not edit manually.
// Run `npm start` or `npm run build` to regenerate from .env
export const environment = {
  production: false,
  supabaseUrl: '',
  supabaseKey: '',
};
